quarkus:
  http:
    port: 8080
  datasource:
    db-kind: mysql
    jdbc:
      max-size: 256
      url: jdbc:mysql://192.168.1.25:3306/ideal-quarkus?useUnicode=true&characterEncoding=utf-8&useAffectedRows=true&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: admin
    password: admin
  thread-pool:
    core-threads: 256
    max-threads: 512
  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}] (%t) %s%e%n"

"%dev":
  quarkus:
    hibernate-orm:
      log:
        sql: false
      database:
        generation: update